# Generated by Django 4.2.3 on 2023-07-26 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_img', models.ImageField(blank=True, upload_to='events')),
                ('event_name', models.CharField(max_length=255)),
                ('event_detail', models.TextField(default='-')),
                ('event_type', models.CharField(choices=[('กิจกรรม', 'กิจกรรม'), ('ค่าย', 'ค่าย')], max_length=64)),
                ('event_date_from', models.DateField()),
                ('event_date_to', models.DateField()),
                ('event_location', models.CharField(default='-', max_length=256)),
                ('event_longitude', models.CharField(default='-', max_length=255)),
                ('annual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.annual')),
            ],
        ),
        migrations.CreateModel(
            name='palace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='palaces')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('nick_name', models.CharField(max_length=128)),
                ('position', models.CharField(max_length=64)),
                ('annual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.annual')),
            ],
        ),
        migrations.CreateModel(
            name='event_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
        ),
        migrations.CreateModel(
            name='event_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
        ),
    ]
